const {app,BrowserWindow,ipcMain}=require('electron'); const {autoUpdater}=require('electron-updater'); const fs=require('fs'),path=require('path');
let win; const sp=()=>path.join(app.getPath('userData'),'settings.json');
function read(){try{return {...{autoCheck:true,openaiKey:''},...JSON.parse(fs.readFileSync(sp(),'utf8'))}}catch{return {autoCheck:true,openaiKey:''}}}
function write(x){fs.writeFileSync(sp(),JSON.stringify(x,null,2));return x}
function safe(s){return {autoCheck:s.autoCheck!==false,hasOpenAIKey:!!s.openaiKey}}
function create(){win=new BrowserWindow({width:1380,height:880,minWidth:900,minHeight:650,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile('index.html')}
function status(state,message){if(win&&!win.isDestroyed())win.webContents.send('update-status',{state,message})}
autoUpdater.autoDownload=true;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on('checking-for-update',()=>status('checking','Checking for updates…'));autoUpdater.on('update-available',i=>status('available',`Downloading ${i.version}…`));autoUpdater.on('update-not-available',()=>status('current','You are up to date.'));autoUpdater.on('download-progress',p=>status('downloading',`Downloading update… ${Math.round(p.percent)}%`));autoUpdater.on('update-downloaded',()=>status('ready','Update ready. Restart to install.'));autoUpdater.on('error',e=>status('error',`Update error: ${e.message}`));
async function aiRequest(input,useWeb=false){const s=read();if(!s.openaiKey)throw new Error('No OpenAI API key saved. Add one in Settings.');const body={model:'gpt-5.6-luna',input};if(useWeb)body.tools=[{type:'web_search'}];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${s.openaiKey}`},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){let m=d?.error?.message||`API error ${r.status}`;if(/credit|quota|billing/i.test(m))m='API credits required. Your OpenAI API account has no available credit. Add credits in OpenAI API Billing, then try again.';throw new Error(m)}let text=d.output_text;if(!text)text=(d.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').filter(Boolean).join('\n');return {text:text||'No response returned.'}}
ipcMain.handle('app-info',()=>({version:app.getVersion(),settings:safe(read())}));ipcMain.handle('save-settings',(_,x)=>{let s=read();if(x.clearKey)s.openaiKey='';else if((x.openaiKey||'').trim())s.openaiKey=x.openaiKey.trim();if(typeof x.autoCheck==='boolean')s.autoCheck=x.autoCheck;write(s);return safe(s)});
ipcMain.handle('school-ask',(_,x)=>{const a=x.attachment;let input=[{role:'user',content:[{type:'input_text',text:`You are a clear, patient school tutor. Teach the method rather than just giving an answer. No education-level labels. Mode: ${x.mode}. Student request: ${x.question}. Organize the answer with short clear sections and lists when useful. For research mode, research current reliable sources, distinguish facts from uncertainty, and end with sources and what to remember.`}]}];if(a&&a.data){const item=/^image\//.test(a.type)?{type:'input_image',image_url:`data:${a.type};base64,${a.data}`}:{type:'input_file',filename:a.name,file_data:`data:${a.type};base64,${a.data}`};input[0].content.push(item)}return aiRequest(input,x.mode==='research')});
ipcMain.handle('plan-ask',(_,x)=>aiRequest(`Explain three illustrative ways a monthly budget of €${x.budget} could be divided among broad categories for someone exploring a ${x.risk} volatility setting and a ${x.goal} goal. This is an educational scenario explorer, not a recommendation. Use broad categories rather than individual securities. For each scenario show euro amounts, percentages, diversification considerations and tradeoffs. Do not rank the scenarios or select one. Make every scenario total exactly €${x.budget}. Use clear sections and include sources for any current factual claims.`,true));
ipcMain.handle('research-ask',(_,x)=>aiRequest(`Research this topic for a personal research dashboard: ${x.topic}. Use current web sources. Be evidence-first, not promotional. If it is an investment/company/asset, cover: what it is, business/industry context, important recent developments, financial or market context when available, growth drivers, risks, competitors/alternatives, upcoming catalysts/events, bull case, bear case, and questions still unanswered. Do not tell the user to buy or sell and do not predict guaranteed returns. If it is not an investment, adapt the report appropriately. End with a concise Sources section naming the sources used and a Research timestamp.`,true));
ipcMain.handle('check-updates',()=>app.isPackaged?autoUpdater.checkForUpdates():status('current','Update checking works in the installed app.'));ipcMain.handle('install-update',()=>autoUpdater.quitAndInstall());
app.whenReady().then(()=>{create();if(app.isPackaged&&read().autoCheck!==false)setTimeout(()=>autoUpdater.checkForUpdates(),3500)});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});